### ISSUE TITLE
Restore bootloader

### ISSUE THREAD

**Issue by gromez** [Zenedith/mir3g-mtd-backup#1]
Hello,

I want to restore the original bootloader of my MIR3G, I have Breed for now.
The only thing I have to do is to download `Bootloader.bin` then flash the bootloader with `mtd write Bootloader.bin Bootloader` ?

Thanks

**Comment by Zenedith** [comment]
Hello,
This is my working padavan "recovery" repository from mir3g, not mir3g original files.
I've used breed so Bootloader.bin can change anything for you.
